services:
  kms-docker:
    container_name: kms-docker
    image: ghcr.io/yuzuk1shimotsuki/kms-docker/stable:latest
    ports:
      - "1688:1688"
    restart: always
    networks:
      - web-network

networks:
  # Set up a replication network
  web-network:
    external: true
