services:
  kms-docker:
    container_name: kms-docker
    build: .
    ports:
      - "1688:1688"
    restart: always
    networks:
      - web-network

networks:
  # Set up a replication network
  web-network:
    external: true
